# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тусовки')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='Дата проведения')),
                ('place', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тусовка',
                'verbose_name_plural': 'Тусовки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='Дата платежа')),
                ('description', models.CharField(max_length=200, verbose_name='Описание платежа')),
                ('cost', models.FloatField()),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('favourite_food', models.CharField(max_length=200, verbose_name='Предпочтения в еде')),
                ('favourite_drinkables', models.CharField(max_length=200, verbose_name='Предпочтения в напитках')),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='MoneyCounterSite.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тусовщик',
                'verbose_name_plural': 'Тусовщики',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile'),
        ),
        migrations.AddField(
            model_name='party',
            name='persons',
            field=models.ManyToManyField(to='MoneyCounterSite.Profile'),
        ),
        migrations.AddField(
            model_name='like',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile'),
        ),
        migrations.AddField(
            model_name='like',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party'),
        ),
    ]
