# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='party',
        ),
        migrations.RemoveField(
            model_name='like',
            name='person',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
