# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_cost',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Общая стоимость тусы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_drinkables',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Предпочтения в напитках'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_food',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Предпочтения в еде'),
        ),
    ]
