# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0002_auto_20170316_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party')),
            ],
        ),
    ]
