# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0002_auto_20170324_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Предпочтение')),
            ],
            options={
                'verbose_name': 'Предпочтение',
                'verbose_name_plural': 'Предпочтения',
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сколько должен отдать денег')),
                ('which_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name='За какую тусовку')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк/Дизлайк', 'verbose_name_plural': 'Лайки/Дизлайки'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='party_id',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_drinkables',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_food',
        ),
        migrations.AddField(
            model_name='like',
            name='flag',
            field=models.NullBooleanField(),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.AddField(
            model_name='repayment',
            name='who_pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='MoneyCounterSite.Profile', verbose_name='Кого должен отдать денег'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='who_receives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_whom', to='MoneyCounterSite.Profile', verbose_name='Кому должен отдать денег'),
        ),
        migrations.AddField(
            model_name='favouritegoods',
            name='person',
            field=models.ManyToManyField(blank=True, db_index=True, to='MoneyCounterSite.Profile', verbose_name='Чье предпочтение'),
        ),
    ]
