# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0004_auto_20170325_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание платежа'),
        ),
    ]
