# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0005_auto_20170316_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Дизлайк', 'verbose_name_plural': 'Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterField(
            model_name='dislike',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Какой тусе'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name='Кто поставил'),
        ),
        migrations.AlterField(
            model_name='like',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Какой тусе'),
        ),
        migrations.AlterField(
            model_name='like',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name='Кто поставил'),
        ),
        migrations.AlterField(
            model_name='party',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='party',
            name='persons',
            field=models.ManyToManyField(to='MoneyCounterSite.Profile', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='party',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.FloatField(verbose_name='Сколько заплатил'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name='Для какой тусовки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Чей платеж'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_drinkables',
            field=models.CharField(blank=True, max_length=200, verbose_name='Предпочтения в напитках'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_food',
            field=models.CharField(blank=True, max_length=200, verbose_name='Предпочтения в еде'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='MoneyCounterSite.Profile', verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
