# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0006_auto_20170317_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Тусовку', 'verbose_name_plural': 'Тусовки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Тусовщика', 'verbose_name_plural': 'Тусовщики'},
        ),
    ]
