# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0007_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='../media/None/no-img.jpg', upload_to='../media/'),
        ),
    ]
