# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0008_auto_20170317_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='party',
        ),
        migrations.RemoveField(
            model_name='like',
            name='party',
        ),
        migrations.AddField(
            model_name='party',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая стоимость тусы'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Кто поставил'),
        ),
        migrations.AlterField(
            model_name='like',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Кто поставил'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_profile_friends_+', to='MoneyCounterSite.Profile', verbose_name='Друзья'),
        ),
    ]
