# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0008_auto_20170325_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='total_cost',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True, verbose_name='Общая стоимость тусы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сколько заплатил'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сколько должен отдать денег'),
        ),
    ]
