# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0009_auto_20170327_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritegoods',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbf\xd0\xbe\xd1\x87\xd1\x82\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='favouritegoods',
            name='person',
            field=models.ManyToManyField(blank=True, db_index=True, to='MoneyCounterSite.Profile', verbose_name=b'\xd0\xa7\xd1\x8c\xd0\xb5 \xd0\xbf\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbf\xd0\xbe\xd1\x87\xd1\x82\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='like',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name=b'\xd0\x9a\xd1\x82\xd0\xbe \xd0\xbf\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xbb'),
        ),
        migrations.AlterField(
            model_name='party',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x82\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='party',
            name='persons',
            field=models.ManyToManyField(to='MoneyCounterSite.Profile', verbose_name=b'\xd0\xa3\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='party',
            name='place',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_cost',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True, verbose_name=b'\xd0\x9e\xd0\xb1\xd1\x89\xd0\xb0\xd1\x8f \xd1\x81\xd1\x82\xd0\xbe\xd0\xb8\xd0\xbc\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd1\x82\xd1\x83\xd1\x81\xd1\x8b'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xba\xd0\xbe \xd0\xb7\xd0\xb0\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xb8\xd0\xbb'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb6\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb6\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name=b'\xd0\x94\xd0\xbb\xd1\x8f \xd0\xba\xd0\xb0\xd0\xba\xd0\xbe\xd0\xb9 \xd1\x82\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name=b'\xd0\xa7\xd0\xb5\xd0\xb9 \xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb6'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_profile_friends_+', to='MoneyCounterSite.Profile', verbose_name=b'\xd0\x94\xd1\x80\xd1\x83\xd0\xb7\xd1\x8c\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xba\xd0\xbe \xd0\xb4\xd0\xbe\xd0\xbb\xd0\xb6\xd0\xb5\xd0\xbd \xd0\xbe\xd1\x82\xd0\xb4\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb5\xd0\xb3'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='which_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name=b'\xd0\x97\xd0\xb0 \xd0\xba\xd0\xb0\xd0\xba\xd1\x83\xd1\x8e \xd1\x82\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2\xd0\xba\xd1\x83'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='who_pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='MoneyCounterSite.Profile', verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xb4\xd0\xbe\xd0\xbb\xd0\xb6\xd0\xb5\xd0\xbd \xd0\xbe\xd1\x82\xd0\xb4\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb5\xd0\xb3'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='who_receives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_whom', to='MoneyCounterSite.Profile', verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd1\x83 \xd0\xb4\xd0\xbe\xd0\xbb\xd0\xb6\xd0\xb5\xd0\xbd \xd0\xbe\xd1\x82\xd0\xb4\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb5\xd0\xb3'),
        ),
    ]
