# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0010_auto_20170327_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritegoods',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Предпочтение'),
        ),
        migrations.AlterField(
            model_name='favouritegoods',
            name='person',
            field=models.ManyToManyField(blank=True, db_index=True, to='MoneyCounterSite.Profile', verbose_name='Чье предпочтение'),
        ),
        migrations.AlterField(
            model_name='like',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Кто поставил'),
        ),
        migrations.AlterField(
            model_name='party',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название тусовки'),
        ),
        migrations.AlterField(
            model_name='party',
            name='persons',
            field=models.ManyToManyField(to='MoneyCounterSite.Profile', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='party',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_cost',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True, verbose_name='Общая стоимость тусы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сколько заплатил'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name='Для какой тусовки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Profile', verbose_name='Чей платеж'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_profile_friends_+', to='MoneyCounterSite.Profile', verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сколько должен отдать денег'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='which_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyCounterSite.Party', verbose_name='За какую тусовку'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='who_pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='MoneyCounterSite.Profile', verbose_name='Кого должен отдать денег'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='who_receives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_whom', to='MoneyCounterSite.Profile', verbose_name='Кому должен отдать денег'),
        ),
    ]
