# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0011_auto_20170327_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='MoneyCounterSite.Profile', verbose_name='Участники'),
        ),
    ]
