# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0013_auto_20170327_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='party',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='like',
            name='positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='is_payed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='persons',
            field=models.ManyToManyField(to='MoneyCounterSite.Profile', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photos/None/no-img.jpg', upload_to='photos/'),
        ),
    ]
