# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyCounterSite', '0014_auto_20170403_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/photos/None/no-img.jpg', upload_to='media/photos/'),
        ),
    ]
